# Generated by Django 2.0.3 on 2018-03-19 22:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=120, unique=True, validators=[django.core.validators.RegexValidator(code='invalid username', message='Username must be Alphanumeric or contains any of the following: ". + -" ', regex='^[a-zA-Z0-9.+-]*$')]),
        ),
    ]
